use_frameworks!

platform :ios, '8.0'

target 'XXWebViewController_Example' do
  pod 'XXWebViewController', :path => '../'

  target 'XXWebViewController_Tests' do
    inherit! :search_paths

    
  end
end
